global:
  enviorments: gitops-for-nginxapp
  name: nginx-app

  image:
    repository: nginx

  replicaCount: 3
  service:
    type: NodePort
    port: 80

  destination:
    server: https://kubernetes.default.svc
    namespace: my-project

  repoURL: https://github.com/EITANPOD/gitOps-nginxapp-chart.git
  targetRevision: HEAD
    